<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComicHoarder.Application\ComicHoarder.Application.csproj" />
    <ProjectReference Include="..\ComicHoarder.Domain\ComicHoarder.Domain.csproj" />
    <ProjectReference Include="..\ComicHoarder.Infrastructure.ComicVine\ComicHoarder.Infrastructure.ComicVine.csproj" />
    <ProjectReference Include="..\ComicHoarder.Infrastructure\ComicHoarder.Infrastructure.csproj" />
    <ProjectReference Include="..\ComicHoarder.Shared\ComicHoarder.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.28" />
    <PackageReference Include="Radzen.Blazor" Version="10.4.4" />
  </ItemGroup>

</Project>
